### ISSUE TITLE
feature: Config flags for zone/map limitations

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/mod-duel-reset#16]
It is currently it is possible to make use of the duel-reset anywhere in the world, which makes it easily abusable. This could be solved by setting certain zones/maps to be whitelisted.
There should be either 
- hardcoded zones where this feature works and a config flag to toggle the check for these
- or config flags for allowed zones/maps

**Comment by Gozzim** [comment]
Yeah, that's why there is a restriction on the age of cooldowns. A PR to set a time for that in the config is also already open.
But you are right, having flags in the config file for zones would be a more consistent solution. Especially in combination with the existing restriction considering there is still room for abuse even when using both.

I'm happy to look into it if you wanna assign me.

**Comment by Winfidonarleyan** [comment]
Can start
